FROM nginx

RUN mkdir -p /consul-template/data
RUN mkdir -p /consul-template/config
ADD https://releases.hashicorp.com/consul-template/0.19.5/consul-template_0.19.5_linux_amd64.tgz /tmp
RUN tar -xvzf /tmp/consul-template_0.19.5_linux_amd64.tgz -C /tmp
RUN mv /tmp/consul-template /usr/local/bin/
RUN rm -f /tmp/consul-template_0.19.5_linux_amd64.tgz

RUN rm -f /etc/nginx/nginx.conf
RUN rm -f /etc/nginx/conf.d/*.conf
COPY nginx.conf /etc/nginx/nginx.conf

# Overload nginx STOPSIGNAL which interfere with consul template
STOPSIGNAL SIGQUIT

EXPOSE 53/udp 53/tcp

CMD ["/usr/local/bin/consul-template", "-template", "/etc/nginx/conf.d/simple.ctmpl:/etc/nginx/conf.d/simple.conf", "-consul-addr", "consul:8500", "-exec", "nginx -g 'daemon off;'"]
