FROM debian:stretch-slim

RUN set -x \
	&& apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y bind9 \
  && rm -rf /var/lib/apt/lists/*

COPY Dockerfile_Bind_Entrypoint.sh /usr/local/bin/entrypoint.sh
COPY toZone /etc/bind/

EXPOSE 53/udp 53/tcp

ENTRYPOINT ["entrypoint.sh"]
CMD ["/usr/sbin/named","-f"]
