version: '3.7'


services:

  #
  # Consul Cluster
  #
  consul:
    image: consul
    environment:
      - CONSUL_CLIENT_INTERFACE=eth0
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -server -bootstrap-expect=3  -retry-join=consul
    networks:
      - saas
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager

  #
  # Registrator on each node
  #
  registrator:
    image: gliderlabs/registrator:latest
    command: -internal consul://consul:8500
    networks:
      - saas
    depends_on:
      - consul
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /tmp/docker.sock
    deploy:
        mode: global


  #
  # Nginx loadbalancer
  #
  nginx:
    image: g4bzh/ngx:latest
    networks:
      - saas
    environment:
      - CONSUL_TEMPLATE_LOG=debug
    ports:
      - target: 53
        published: 53
        protocol: tcp
      - target: 53
        published: 53
        protocol: udp
    depends_on:
      - consul
    deploy:
      mode: global
  #
  # MongoDB Master
  # mkdir /mongodb
  #
  mongodbPrimary:
    image: bitnami/mongodb:latest
    networks:
      - saas
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.labels.mongodb == primary


  #
  # MongoDB Secondary
  #
  mongodbSecondary:
    image: bitnami/mongodb:latest
    networks:
      - saas
    depends_on:
      - mongodbPrimary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodbPrimary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
          - node.labels.mongodb != primary


  #
  # MongoDB arbitrer
  #
  mongodbArbiter:
    image: bitnami/mongodb:latest
    networks:
      - saas
    depends_on:
      - mongodbPrimary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodbPrimary
      - MONGODB_PRIMARY_PORT_NUMBER=27017


  #
  # DNS Config
  #
  dnscfg:
    image: g4bzh/dnscfg:latest
    networks:
      - saas
    environment:
      - DBURL=mongodbSecondary:27017,mongodbPrimary:27017
      - DB=dnscfg
      - DBCOL=data
    ports:
      - target: 8053
        published: 8053
        protocol: tcp
    depends_on:
    - mongodbPrimary
    deploy:
      replicas: 2


networks:
  saas:
    driver: overlay
    ipam:
      config:
      - subnet: 242.0.0.0/8
