FROM nginx

RUN rm -f /etc/nginx/nginx.conf
RUN rm -f /etc/nginx/conf.d/*.conf
COPY nginx.conf /etc/nginx/nginx.conf

# Overload nginx STOPSIGNAL
STOPSIGNAL SIGQUIT

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
